version: "3"
services:
    web:
        container_name: web
        env_file: ".env"
        restart: always
        build: .
        ports: 
            - 3000:3000
        links:
            - db
        volumes: 
            - .:/usr/src/app
    db:
        image: "postgres:latest"
        container_name: db
        env_file: ".env"
        ports: 
            - 5432:5432
        volumes: 
            - psql:/var/lib/postgresql/data
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    psql:
        